DEPENDPATH  += $$PWD
INCLUDEPATH += $$PWD

MEANSHIFT_TARGET_NAME = meanshift
MEANSHIFT_TARGET_NAME = $$join(MEANSHIFT_TARGET_NAME,,,$$BUILD_CFG_SFX)

LIBS += -L$$ROOT_DIR/bin -l$$MEANSHIFT_TARGET_NAME
